name = input("Enter name: ")
age = input("Enter age: ")
year = input("Enter year: ")
course = input("Enter course: ")
height = input("Enter height (cm): ")
weight = input("Enter weight (kg): ")
nat = input("Enter nationality: ")
col = input("Enter favourite colour: ")
pet = input("Do you have any pets? ")
food = input("Favourite food? ")
print(f"My name is {name} and my age {age} years old. I am in year {year}, {course} at BSU, I am {height}cm tall, and i weigh {weight}kg. I am {nat} and my favorite color is {col}. I have {pet}. My favorite food is {food}.  ")