name = input("Enter name: ")
age = input("Enter age: ")
year = input("Enter year: ")
course = input("Enter course: ")
height = input("Enter height (cm): ")
weight = input("Enter weight (kg): ")
nat = input("Enter nationality: ")
col = input("Enter favourite colour: ")
pet = input("Do you have any pets? ")
food = input("Favourite food? ")
print ("my name is " + name +", I am "+ age +"  old. "+ "I am in " + year + " " + course + " at BSU. "+ "I am " + height+ "cm tall, and i weigh " + weight+ " kilos. "+ "I am " + nat + " and my favourite color is "+ col + ". I have a "+ pet + ". and my favourite food is "+ food + ".") 